# Premier Healthcare Platform Tours Configuration
# This file defines all the tours available in the platform

tours:
  # Quick Tour Guide - introduces the platform to new users
  quick_tour:
    id: quick_tour
    name: Quick Tour Guide
    description: A quick tour of the Premier Healthcare Platform
    initialStep: tour_intro
    steps:
      - id: navbar
        title: Navigation
        description: Use the navigation bar to move between different sections of the application. You can access appointments, patient intake, your profile, and more.
        selector: "nav#navbar"
        position: bottom
        audioFile: welcome/navigation-intro.mp3
      
      - id: appointments
        title: Appointment Scheduling
        description: Let's start with appointments. Our platform makes it easy to schedule, reschedule, or cancel appointments.
        selector: "a[href='/appointments']"
        position: bottom
        audioFile: appointment/appointment_scheduling.mp3
      
      - id: patient_intake
        title: Patient Intake
        description: To save time at the clinic, please complete your registration and medical history online before your appointment so we can streamline our services for you.
        selector: "a[href*='/intake']"
        position: bottom
        audioFile: patient-intake/patient_intake_button.mp3
      
      - id: my_profile
        title: My Profile
        description: View and update your personal information, contact details, and preferences in your profile section.
        selector: "a[href*='/patient']"
        position: bottom
        audioFile: my-profile/my-profile-section.mp3
      
      - id: referrals
        title: Referrals
        description: Track and manage your referrals to specialists. Stay informed at every step of the referral process.
        selector: "a[href='/referrals']"
        position: bottom
        audioFile: referrals/referrals_button.mp3
      - id: billing
        title: Billing & Insurance
        description: In the billing and insurance section, you can manage insurance information, view statements, and make secure payments. All financial and health data is protected in compliance with HIPAA standards and robust security protocols.
        selector: "#billing-menu button"
        position: top
        audioFile: payment/billing_and_insurance_nav.mp3
      
      - id: help
        title: Need Help?
        description: Click this button anytime you need assistance with the platform. Our AI assistant will guide you through any process.
        selector: "a.need-help-button"
        position: left
        audioFile: need-help/need_help_button.mp3
      - id: tour_complete
        title: Tour Complete!
        description: "Congratulations! You've completed the quick tour of Premier Healthcare. Feel free to explore the platform on your own."
        audioFile: welcome/tour_complete.mp3

  # Add more tours below as needed
  # Example: patient_intake_tour:
  #   name: Patient Intake Guide
  #   ...